/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as shopCartIndexRouteImport } from './routes/(shop)/cart/index'
import { Route as shopProductsIndexRouteImport } from './routes/(shop)/products/index'
import { Route as shopProductsSlugRouteImport } from './routes/(shop)/products/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const shopCartIndexRoute = shopCartIndexRouteImport.update({
  id: '/(shop)/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const shopProductsIndexRoute = shopProductsIndexRouteImport.update({
  id: '/(shop)/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const shopProductsSlugRoute = shopProductsSlugRouteImport.update({
  id: '/(shop)/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products/$slug': typeof shopProductsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/cart/': typeof shopCartIndexRoute
  '/products/': typeof shopProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products/$slug': typeof shopProductsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/cart': typeof shopCartIndexRoute
  '/products': typeof shopProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(shop)/products/$slug': typeof shopProductsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(shop)/cart/': typeof shopCartIndexRoute
  '/(shop)/products/': typeof shopProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/products/$slug' | '/api/auth/$' | '/cart/' | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/products/$slug' | '/api/auth/$' | '/cart' | '/products'
  id:
    | '__root__'
    | '/'
    | '/(shop)/products/$slug'
    | '/api/auth/$'
    | '/(shop)/cart/'
    | '/(shop)/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  shopProductsSlugRoute: typeof shopProductsSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  shopCartIndexRoute: typeof shopCartIndexRoute
  shopProductsIndexRoute: typeof shopProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(shop)/cart/': {
      id: '/(shop)/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof shopCartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(shop)/products/': {
      id: '/(shop)/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof shopProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(shop)/products/$slug': {
      id: '/(shop)/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof shopProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  shopProductsSlugRoute: shopProductsSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  shopCartIndexRoute: shopCartIndexRoute,
  shopProductsIndexRoute: shopProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
