/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteRouteImport } from './routes/_shop/route'
import { Route as ShopIndexRouteImport } from './routes/_shop/index'
import { Route as ShopCartIndexRouteImport } from './routes/_shop/cart/index'
import { Route as ShopProductsIndexRouteImport } from './routes/_shop/products/index'
import { Route as ShopProductsSlugRouteImport } from './routes/_shop/products/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ShopRouteRoute = ShopRouteRouteImport.update({
  id: '/_shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRouteRoute,
} as any)
const ShopCartIndexRoute = ShopCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => ShopRouteRoute,
} as any)
const ShopProductsIndexRoute = ShopProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => ShopRouteRoute,
} as any)
const ShopProductsSlugRoute = ShopProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => ShopRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShopIndexRoute
  '/products/$slug': typeof ShopProductsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/cart/': typeof ShopCartIndexRoute
  '/products/': typeof ShopProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ShopIndexRoute
  '/products/$slug': typeof ShopProductsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/cart': typeof ShopCartIndexRoute
  '/products': typeof ShopProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shop': typeof ShopRouteRouteWithChildren
  '/_shop/': typeof ShopIndexRoute
  '/_shop/products/$slug': typeof ShopProductsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_shop/cart/': typeof ShopCartIndexRoute
  '/_shop/products/': typeof ShopProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/products/$slug' | '/api/auth/$' | '/cart/' | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/products/$slug' | '/api/auth/$' | '/cart' | '/products'
  id:
    | '__root__'
    | '/_shop'
    | '/_shop/'
    | '/_shop/products/$slug'
    | '/api/auth/$'
    | '/_shop/cart/'
    | '/_shop/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShopRouteRoute: typeof ShopRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shop': {
      id: '/_shop'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShopRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop/': {
      id: '/_shop/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/_shop/cart/': {
      id: '/_shop/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof ShopCartIndexRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/_shop/products/': {
      id: '/_shop/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ShopProductsIndexRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/_shop/products/$slug': {
      id: '/_shop/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ShopProductsSlugRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShopRouteRouteChildren {
  ShopIndexRoute: typeof ShopIndexRoute
  ShopProductsSlugRoute: typeof ShopProductsSlugRoute
  ShopCartIndexRoute: typeof ShopCartIndexRoute
  ShopProductsIndexRoute: typeof ShopProductsIndexRoute
}

const ShopRouteRouteChildren: ShopRouteRouteChildren = {
  ShopIndexRoute: ShopIndexRoute,
  ShopProductsSlugRoute: ShopProductsSlugRoute,
  ShopCartIndexRoute: ShopCartIndexRoute,
  ShopProductsIndexRoute: ShopProductsIndexRoute,
}

const ShopRouteRouteWithChildren = ShopRouteRoute._addFileChildren(
  ShopRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ShopRouteRoute: ShopRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
